c_stdlib_version:          # [osx_64 and osx_arm64]
  - "10.15"                # [osx_64 and osx_arm64]
MACOSX_SDK_VERSION:        # [osx_64 and osx_arm64]
  - "13.3"                # [osx_64 and osx_arm64]
mpi:
- mpich
- openmpi
- nompi

channel_targets:
  - abmazitov main

