{% set build = 0 %}
{% set version = "0.0.1" %}

package:
  name: lammps-metatensor
  version: {{ version }}

source:
  git_url: https://github.com/metatensor/lammps.git
  git_depth: 1 # (Defaults to -1/not shallow)

build:
  number: {{ build }}
  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  skip: true  # [win]
  string: cpu_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ mpi_prefix }}_{{ PKG_BUILDNUM }}


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - rust
    - make
    - cmake
  host:
    - {{ mpi }}  # [mpi != 'nompi']
    - libtorch  =*=cpu*
  run:
    - {{ mpi }}  # [mpi != 'nompi']

about:
  home: https://docs.metatensor.org/latest/index.html
  license: BSD-3-Clause
  license_family: BSD
  summary: 'Metatensor-enabled version of LAMMPS'
  description: |
    Metatensor-enabled version of LAMMPS
  doc_url: https://docs.metatensor.org/latest/atomistic/engines/lammps.html
  dev_url: https://github.com/metatensor/lammps

extra:
  recipe-maintainers:
    - abmazitov

