{% set version = "4Feb2025" %}
{% set build = 1 %}
{% set cuda_major = environ.get("cuda_compiler_version", "0.0").split(".")[0]|int %}

# Use a higher build number for the CUDA variant, to ensure that it's
# preferred by conda's solver, and it's preferentially
# installed where the platform supports it.
{% if cuda_compiler_version != "None" %}
{% set build = build + 200 %}
{% endif %}

package:
  name: lammps-metatensor
  version: {{ version }}

source:
  git_url: https://github.com/metatensor/lammps.git
  depth: 1
{% if cuda_compiler_version != "None" %}
  git_rev: kokkos-pet-mad
{% endif %}
build:
  number: {{ build }}
  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  skip: True  # [win]
  skip: True  # [cuda_compiler_version == "10.2"]
  skip: True  # [cuda_compiler_version == "11.2"]
  track_features:
    - cudatoolkit               # [cuda_compiler_version != "None"]
  string: cuda{{ cuda_compiler_version | replace('.', '') }}_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ mpi_prefix }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ CONDA_PY }}_h{{ PKG_HASH }}_{{ mpi_prefix }}_{{ PKG_BUILDNUM }} # [cuda_compiler_version == "None"]
  script_env:
    - Kokkos_OPT_ARGS=-DKokkos_ARCH_HOPPER90=ON # [cuda_compiler_version != "None"]


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ compiler('cuda') }}    # [cuda_compiler_version != "None"]
    - rust
    - make
    - cmake=3.28
  host:
    - {{ mpi }}  # [mpi != 'nompi']
{% if cuda_major == 11 %}
    - cuda-version=11 # [cuda_compiler_version != "None"]
    - cudatoolkit # [cuda_compiler_version != "None"]
{% endif %}
{% if cuda_major == 12 %}
    - cuda-version=12 # [cuda_compiler_version != "None"]
    - cuda-cudart # [cuda_compiler_version != "None"]
    - nvidia/label/cuda-12.1.0::cuda-toolkit # [cuda_compiler_version != "None"]
{% endif %}
    - libtorch  =*=cpu*
  run:
    - {{ mpi }}  # [mpi != 'nompi']
    - __cuda  # [cuda_compiler_version != "None"]

about:
  home: https://docs.metatensor.org/latest/index.html
  license: BSD-3-Clause
  license_family: BSD
  summary: 'Metatensor-enabled version of LAMMPS'
  description: |
    Metatensor-enabled version of LAMMPS
  doc_url: https://docs.metatensor.org/latest/atomistic/engines/lammps.html
  dev_url: https://github.com/metatensor/lammps

extra:
  recipe-maintainers:
    - abmazitov

